export interface Posten {
  id?: number,
  aufwand?: number ,
  ertrag?: number,
  volumen?: number,
  umsatz?: number,
  kosten?: number,
  anzahl?: number,
  aquisitionsweg?: string,
  erfassungsart?: string,
  gebuehrenart?: string,
  individualprodukt?: number,
  isinNummer?: string,
  ordernummer?: number,
  provisionstyp?: string,
  sparte?: string,
  standardprodukt?: number,
  tarif?: string,
  textschluesselgruppe?: number,
  vpPostenidentifier1?: string,
  vpPostenidentifier2?: string,
  vpPostenidentifier3?: string,
  vpPostenidentifier4?: string,
  vpPostenidentifier5?: string,
  wertpapierkennnummer?: string,
  zuwachsvertrag?: string
}
